name: Puppyroo
favicon: null
layout_spectrum: 0.00251
typography_spectrum: 0.26655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#bfbcb6'
    - '#8a8a8a'
    - '#2c87df'
  brandStrength: 0.9651836762204766
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.9798457804135978
purpose: []
